import { auth } from "@/auth";
import type { Metadata } from "next";
import "./globals.css";
import { Header } from "./lib/components";


export const metadata: Metadata = {
  title: "ZEVA",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  if (!!session?.user) {
    // Authenticated layout
    return (
      <html lang="en">
        <body
          className={`antialiased`}
        >
          <Header session={session} />
          {children}
        </body>
      </html>
    );
  } else {
    // Unauthenticated layout
    return (
      <html lang="en">
        <body
          className={`antialiased`}
        >
          {children}
        </body>
      </html>
    );
  }
}
